apiVersion: v1
kind: Pod
metadata:
  name: pod-2-example
  labels:
    app: second-pod
spec:
  containers:
    - name: container-pod-2
      image: nginx:latest
      ports:
        - containerPort: 80
